language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"

after_success:
  - echo "passed the test now building"
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_DEPLOY_KEY
  app: read-meee
  on:
    repo: Siddant/project-4
