language: node_js
node_js: 10.15.1
#   - 7
#   - 8

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: "Install"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.14.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install: yarn
      script: echo 'build complete'
    - stage: "Tests" # naming the Tests stage
      name: "Unit Tests" # names the first Tests stage job
      script: yarn test
    - name: "Unit Tests 1"
      script: yarn testSecond
    - name: "Unit Tests 3"
    - script:
        - yarn test
        - echo "passed the test now building"
    - stage: "Tests 2" # naming the Tests stage
      name: "Unit Tests 2" # names the first Tests stage job
      script: yarn testSecond
    # - stage: "build"
    #   if: branch = master AND type != pull_request
    #   name: "building project" # names the second Tests stage job
    #   script:
    #     - echo "passed the test now building"
    #     - yarn build
    #     - git add .
    #     - git commit -m "ready to deploy"
    # - stage: "deploy"
    #   if: branch = master AND type != pull_request
    #   name: "Deploy to heroku"
    #   script: skip
    #   deploy:
    #     provider: heroku
    #     api_key:
    #       secure: $HEROKU_DEPLOY_KEY
    #     app: read-meee
    #     on:
    #       branch: master
    #       repo: Siddant/project-4
